### ISSUE TITLE
Installation error also eslint error askin to update to 7.0 or higher

### ISSUE THREAD

**Issue by ayush1921** [hemanth-kotagiri/jntuh-results#11]
yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @faker-js/faker@6.0.0-beta.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.9"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by hemanth-kotagiri** [comment]
Hey there @ayush1921 . Your current node version is 12.22.9. Please update it to the latest version(>=14.0.0) to run the project.
